export const dashboardColorTokens = {
  background: '#090b10',
  border: 'rgba(226, 232, 240, 0.14)',
  error: '#b42318',
  errorContrast: '#ffe4e0',
  pageBackground:
    'radial-gradient(circle at top left, rgba(204, 214, 34, 0.15), transparent 32rem), linear-gradient(135deg, #090b10, #141417)',
  primary: '#ccd622',
  primaryLight: '#e6ef57',
  surface: 'linear-gradient(145deg, rgba(26, 29, 35, 0.98), rgba(15, 17, 21, 0.98))',
  success: '#12805c',
  successContrast: '#dcfff3',
  textDisabled: 'rgba(245, 245, 244, 0.42)',
  textPrimary: '#fafaf9',
  textSecondary: '#b7b8ad',
} as const;

export const dashboardLayoutTokens = {
  actionButtonFontSize: 18,
  actionButtonGap: 2,
  actionButtonMinWidth: 280,
  actionButtonMinHeight: 78,
  actionButtonProgressSize: 24,
  appMaxWidth: 1120,
  appPaddingDesktop: 5,
  appPaddingMobile: 2,
  appPaddingTablet: 4,
  appVerticalPaddingDesktop: 6,
  appVerticalPaddingMobile: 3,
  appVerticalPaddingTablet: 5,
  bodyLineHeight: 1.35,
  borderRadius: 8,
  borderWidth: 1,
  cardShadowLevel: 4,
  dashboardTitleFontSize: 15,
  dashboardTitleFontWeight: 700,
  fontFamily:
    '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
  focusOutlineOffset: 3,
  focusOutlineWidth: 2,
  headingLineHeight: 1.08,
  heroShadowLevel: 8,
  logoHeight: 58,
  sectionGap: 4,
  sectionTitleFontSize: 28,
  sectionTitleFontWeight: 700,
  serviceCardGap: 2,
  serviceCardMinHeight: 104,
  serviceCardPadding: 3,
  serviceGridColumnsDesktop: 3,
  serviceGridColumnsTablet: 2,
  serviceGridGap: 2,
  serviceIconFrameSize: 58,
  serviceIconSize: 30,
  serviceSectionGap: 2,
  serviceTitleFontSize: 20,
  serviceTitleFontWeight: 700,
  serverNameFontSize: 48,
  serverNameFontWeight: 800,
  statusCardPaddingDesktop: 4,
  statusCardPaddingMobile: 3,
  statusContentGap: 3,
  statusContentTopPadding: 4,
  statusHeaderGap: 2,
  statusIconFrameSize: 72,
  statusIconSize: 40,
  statusChipProgressSize: 18,
  statusLoadingBarHeight: 4,
} as const;
